services:
  api:
    image: ml-stock-market-predictor:latest
    build:
      context: .
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "10000:10000"
    volumes:
      - "./data:/app/data"
    environment:
      DATABASE_URL: "sqlite:///data/predictions.db"
      TRAIN_KERNEL_STARTUP_TIMEOUT_S: "20000"
